/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TipSplitter } from "./TipSplitter";
export * as factories from "./factories";
export { TipSplitter__factory } from "./factories/TipSplitter__factory";
