// Auto-generated file. Do not edit manually.
// Generated by scripts/generate-chains.js
// Date: 2026-02-08T00:39:27.334Z

export interface ChainConfig {
    id: number;
    name: string;
    key: string;
    logoURI?: string;
    nativeToken: {
        symbol: string;
        decimals: number;
        name: string;
        logoURI?: string;
        address: string;
    };
    metamask: {
        chainId: string;
        chainName: string;
        nativeCurrency: {
            name: string;
            symbol: string;
            decimals: number;
        };
        rpcUrls: string[];
        blockExplorerUrls: string[];
    };
}

export const evmChains: ChainConfig[] = [
    {
        "id": 1,
        "name": "Ethereum",
        "key": "eth",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/ethereum.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x1",
            "blockExplorerUrls": [
                "https://etherscan.io/"
            ],
            "chainName": "Ethereum Mainnet",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://ethereum-rpc.publicnode.com",
                "https://eth.drpc.org"
            ]
        }
    },
    {
        "id": 42161,
        "name": "Arbitrum",
        "key": "arb",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/arbitrum.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xa4b1",
            "blockExplorerUrls": [
                "https://arbiscan.io/"
            ],
            "chainName": "Arbitrum One",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://arb1.arbitrum.io/rpc",
                "https://arbitrum-one-rpc.publicnode.com",
                "https://arbitrum.drpc.org"
            ]
        }
    },
    {
        "id": 8453,
        "name": "Base",
        "key": "bas",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/base.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x2105",
            "blockExplorerUrls": [
                "https://basescan.org/"
            ],
            "chainName": "Base",
            "nativeCurrency": {
                "name": "Ethereum",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.base.org",
                "https://base-rpc.publicnode.com",
                "https://base.drpc.org"
            ]
        }
    },
    {
        "id": 1337,
        "name": "Hyperliquid",
        "key": "hpl",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/hyperliquid.svg",
        "nativeToken": {
            "symbol": "USDC",
            "decimals": 6,
            "name": "USD Coin (Perps)",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png",
            "address": "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
        },
        "metamask": {
            "chainId": "0xa4b1",
            "blockExplorerUrls": [
                "https://app.hyperliquid.xyz/explorer/"
            ],
            "chainName": "Hyperliquid",
            "nativeCurrency": {
                "name": "USDC",
                "symbol": "USDC",
                "decimals": 6
            },
            "rpcUrls": [
                "https://li.quest/v1/rpc/1337"
            ]
        }
    },
    {
        "id": 999,
        "name": "HyperEVM",
        "key": "hyp",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/hyperevm.svg",
        "nativeToken": {
            "symbol": "HYPE",
            "decimals": 18,
            "name": "HYPE",
            "logoURI": "https://static.debank.com/image/hyper_token/logo_url/hyper/0b3e288cfe418e9ce69eef4c96374583.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x3e7",
            "blockExplorerUrls": [
                "https://hyperevmscan.io/"
            ],
            "chainName": "HyperEVM",
            "nativeCurrency": {
                "name": "HYPE",
                "symbol": "HYPE",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.hyperliquid.xyz/evm",
                "https://rpc.hyperlend.finance",
                "https://hyperliquid-json-rpc.stakely.io",
                "https://hyperliquid.drpc.org",
                "https://rpc.hypurrscan.io"
            ]
        }
    },
    {
        "id": 143,
        "name": "Monad",
        "key": "mon",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/monad.svg",
        "nativeToken": {
            "symbol": "MON",
            "decimals": 18,
            "name": "Monad",
            "logoURI": "https://static.debank.com/image/monad_token/logo_url/monad/9df1611d238781f78045fba9101359a3.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x8f",
            "blockExplorerUrls": [
                "https://monadscan.com/"
            ],
            "chainName": "Monad",
            "nativeCurrency": {
                "name": "MON",
                "symbol": "MON",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.monad.xyz",
                "https://rpc1.monad.xyz",
                "https://rpc2.monad.xyz",
                "https://rpc3.monad.xyz",
                "https://rpc4.monad.xyz",
                "https://rpc-mainnet.monadinfra.com"
            ]
        }
    },
    {
        "id": 56,
        "name": "BSC",
        "key": "bsc",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bsc.svg",
        "nativeToken": {
            "symbol": "BNB",
            "decimals": 18,
            "name": "BNB",
            "logoURI": "https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x38",
            "blockExplorerUrls": [
                "https://bscscan.com/"
            ],
            "chainName": "BNB Smart Chain Mainnet",
            "nativeCurrency": {
                "name": "BNB",
                "symbol": "BNB",
                "decimals": 18
            },
            "rpcUrls": [
                "https://bsc-dataseed.binance.org",
                "https://bsc-dataseed.bnbchain.org",
                "https://bsc-rpc.publicnode.com",
                "https://bsc-dataseed1.defibit.io",
                "https://bsc-dataseed1.ninicoin.io"
            ]
        }
    },
    {
        "id": 10,
        "name": "OP Mainnet",
        "key": "opt",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/optimism.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xa",
            "blockExplorerUrls": [
                "https://optimistic.etherscan.io/"
            ],
            "chainName": "OP Mainnet",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.optimism.io/",
                "https://optimism-rpc.publicnode.com",
                "https://optimism.drpc.org"
            ]
        }
    },
    {
        "id": 137,
        "name": "Polygon",
        "key": "pol",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/polygon.svg",
        "nativeToken": {
            "symbol": "POL",
            "decimals": 18,
            "name": "Polygon Ecosystem Token",
            "logoURI": "https://static.debank.com/image/matic_token/logo_url/matic/6f5a6b6f0732a7a235131bd7804d357c.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x89",
            "blockExplorerUrls": [
                "https://polygonscan.com/"
            ],
            "chainName": "Polygon Mainnet",
            "nativeCurrency": {
                "name": "Polygon Ecosystem Token",
                "symbol": "POL",
                "decimals": 18
            },
            "rpcUrls": [
                "https://polygon-bor-rpc.publicnode.com",
                "https://polygon.drpc.org",
                "https://polygon-rpc.com"
            ]
        }
    },
    {
        "id": 43114,
        "name": "Avalanche",
        "key": "ava",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/avalanche.svg",
        "nativeToken": {
            "symbol": "AVAX",
            "decimals": 18,
            "name": "AVAX",
            "logoURI": "https://static.debank.com/image/avax_token/logo_url/avax/0b9c84359c84d6bdd5bfda9c2d4c4a82.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xa86a",
            "blockExplorerUrls": [
                "https://snowtrace.io/"
            ],
            "chainName": "Avalanche C-Chain",
            "nativeCurrency": {
                "name": "AVAX",
                "symbol": "AVAX",
                "decimals": 18
            },
            "rpcUrls": [
                "https://api.avax.network/ext/bc/C/rpc",
                "https://avalanche-c-chain-rpc.publicnode.com",
                "https://avalanche.drpc.org"
            ]
        }
    },
    {
        "id": 100,
        "name": "Gnosis",
        "key": "dai",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/gnosis.svg",
        "nativeToken": {
            "symbol": "xDAI",
            "decimals": 18,
            "name": "xDAI Native Token",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x64",
            "blockExplorerUrls": [
                "https://gnosis.blockscout.com/"
            ],
            "chainName": "Gnosis",
            "nativeCurrency": {
                "name": "XDAI",
                "symbol": "XDAI",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.gnosischain.com",
                "https://gnosis-rpc.publicnode.com",
                "https://gnosis.drpc.org"
            ]
        }
    },
    {
        "id": 1088,
        "name": "Metis",
        "key": "mam",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/metis.svg",
        "nativeToken": {
            "symbol": "METIS",
            "decimals": 18,
            "name": "METIS",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/9640.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x440",
            "blockExplorerUrls": [
                "https://andromeda-explorer.metis.io/"
            ],
            "chainName": "Metis Andromeda Mainnet",
            "nativeCurrency": {
                "name": "METIS",
                "symbol": "METIS",
                "decimals": 18
            },
            "rpcUrls": [
                "https://metis-public.nodies.app",
                "https://andromeda.metis.io",
                "https://metis.drpc.org"
            ]
        }
    },
    {
        "id": 1135,
        "name": "Lisk",
        "key": "lsk",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/lisk.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x46f",
            "blockExplorerUrls": [
                "https://blockscout.lisk.com/"
            ],
            "chainName": "Lisk",
            "nativeCurrency": {
                "name": "Ethereum",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.api.lisk.com",
                "https://lisk.drpc.org"
            ]
        }
    },
    {
        "id": 122,
        "name": "FUSE",
        "key": "fus",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/fuse.svg",
        "nativeToken": {
            "symbol": "FUSE",
            "decimals": 18,
            "name": "FUSE",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/5634.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x7a",
            "blockExplorerUrls": [
                "https://explorer.fuse.io/"
            ],
            "chainName": "Fuse Mainnet",
            "nativeCurrency": {
                "name": "FUSE",
                "symbol": "FUSE",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.fuse.io",
                "https://fuse.drpc.org"
            ]
        }
    },
    {
        "id": 1284,
        "name": "Moonbeam",
        "key": "moo",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/moonbeam.svg",
        "nativeToken": {
            "symbol": "GLMR",
            "decimals": 18,
            "name": "GLMR",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/6836.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x504",
            "blockExplorerUrls": [
                "https://moonbeam.moonscan.io/"
            ],
            "chainName": "Moonbeam",
            "nativeCurrency": {
                "name": "GLMR",
                "symbol": "GLMR",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.api.moonbeam.network",
                "https://moonbeam-rpc.publicnode.com",
                "https://moonbeam.drpc.org"
            ]
        }
    },
    {
        "id": 130,
        "name": "Unichain",
        "key": "uni",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/unichain.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x82",
            "blockExplorerUrls": [
                "https://unichain.blockscout.com/",
                "https://uniscan.xyz/"
            ],
            "chainName": "Unichain",
            "nativeCurrency": {
                "name": "Ether",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.unichain.org"
            ]
        }
    },
    {
        "id": 1329,
        "name": "Sei",
        "key": "sei",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/sei.svg",
        "nativeToken": {
            "symbol": "SEI",
            "decimals": 18,
            "name": "SEI",
            "logoURI": "https://cdn.sei.io/sei-app/sei-icon.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x531",
            "blockExplorerUrls": [
                "https://seiscan.io/"
            ],
            "chainName": "Sei Network",
            "nativeCurrency": {
                "name": "SEI",
                "symbol": "SEI",
                "decimals": 18
            },
            "rpcUrls": [
                "https://evm-rpc.sei-apis.com"
            ]
        }
    },
    {
        "id": 13371,
        "name": "Immutable zkEVM",
        "key": "imx",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/imx.svg",
        "nativeToken": {
            "symbol": "IMX",
            "decimals": 18,
            "name": "IMX",
            "logoURI": "https://checkout-cdn.immutable.com/v1/blob/img/tokens/imx.svg",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x343b",
            "blockExplorerUrls": [
                "https://explorer.immutable.com/"
            ],
            "chainName": "Immutable",
            "nativeCurrency": {
                "name": "ImmutableX",
                "symbol": "IMX",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.immutable.com/",
                "https://immutable-zkevm.drpc.org"
            ]
        }
    },
    {
        "id": 14,
        "name": "Flare",
        "key": "flr",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/flare.svg",
        "nativeToken": {
            "symbol": "FLR",
            "decimals": 18,
            "name": "Flare",
            "logoURI": "https://static.debank.com/image/flr_token/logo_url/flr/c7d8087092d5d7b80794630612afb32e.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xe",
            "blockExplorerUrls": [
                "https://flarescan.com/"
            ],
            "chainName": "Flare",
            "nativeCurrency": {
                "name": "Flare",
                "symbol": "FLR",
                "decimals": 18
            },
            "rpcUrls": [
                "https://flare-api.flare.network/ext/C/rpc"
            ]
        }
    },
    {
        "id": 146,
        "name": "Sonic",
        "key": "son",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/sonic.svg",
        "nativeToken": {
            "symbol": "S",
            "decimals": 18,
            "name": "S",
            "logoURI": "https://static.debank.com/image/sonic_token/logo_url/0x039e2fb66102314ce7b64ce5ce3e5183bc94ad38/b4cc70d040518a88adac18d906fcbfff.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x92",
            "blockExplorerUrls": [
                "https://explorer.soniclabs.com/",
                "https://sonicscan.org/"
            ],
            "chainName": "Sonic Network",
            "nativeCurrency": {
                "name": "Sonic",
                "symbol": "S",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.soniclabs.com",
                "https://sonic.drpc.org"
            ]
        }
    },
    {
        "id": 1480,
        "name": "Vana",
        "key": "van",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/vana.svg",
        "nativeToken": {
            "symbol": "VAN",
            "decimals": 18,
            "name": "Vana",
            "logoURI": "https://static.debank.com/image/vana_token/logo_url/vana/4e286c230ccb1e83967dc85edefbc513.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x5c8",
            "blockExplorerUrls": [
                "https://vanascan.io/"
            ],
            "chainName": "Vana",
            "nativeCurrency": {
                "name": "VAN",
                "symbol": "VAN",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.vana.org"
            ]
        }
    },
    {
        "id": 1625,
        "name": "Gravity",
        "key": "gra",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/gravity.svg",
        "nativeToken": {
            "symbol": "G",
            "decimals": 18,
            "name": "G",
            "logoURI": "https://assets.gravity.xyz/token_logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x659",
            "blockExplorerUrls": [
                "https://explorer.gravity.xyz/"
            ],
            "chainName": "Gravity Alpha Mainnet",
            "nativeCurrency": {
                "name": "G",
                "symbol": "G",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.gravity.xyz/"
            ]
        }
    },
    {
        "id": 167000,
        "name": "Taiko",
        "key": "tai",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/taiko.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x28c58",
            "blockExplorerUrls": [
                "https://taikoscan.io/"
            ],
            "chainName": "Taiko Mainnet",
            "nativeCurrency": {
                "name": "Ethereum",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.mainnet.taiko.xyz",
                "https://rpc.taiko.xyz"
            ]
        }
    },
    {
        "id": 1868,
        "name": "Soneium",
        "key": "soe",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/soneium.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x74c",
            "blockExplorerUrls": [
                "https://soneium.blockscout.com/"
            ],
            "chainName": "Soneium",
            "nativeCurrency": {
                "name": "Ether",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.soneium.org/"
            ]
        }
    },
    {
        "id": 1923,
        "name": "Swellchain",
        "key": "swl",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/swell.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x783",
            "blockExplorerUrls": [
                "https://swellchainscan.io/"
            ],
            "chainName": "Swellchain",
            "nativeCurrency": {
                "name": "Ether",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://swell-mainnet.alt.technology"
            ]
        }
    },
    {
        "id": 2020,
        "name": "Ronin",
        "key": "ron",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/ronin.svg",
        "nativeToken": {
            "symbol": "RON",
            "decimals": 18,
            "name": "Ronin",
            "logoURI": "https://static.debank.com/image/ron_token/logo_url/0xe514d9deb7966c8be0ca922de8a064264ea6bcd4/f65d4fdc17d5533c59ebcd6eb1f47320.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x7e4",
            "blockExplorerUrls": [
                "https://app.roninchain.com/"
            ],
            "chainName": "Ronin",
            "nativeCurrency": {
                "name": "RON",
                "symbol": "RON",
                "decimals": 18
            },
            "rpcUrls": [
                "https://api.roninchain.com/rpc"
            ]
        }
    },
    {
        "id": 204,
        "name": "opBNB",
        "key": "opb",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/opbnb.svg",
        "nativeToken": {
            "symbol": "BNB",
            "decimals": 18,
            "name": "BNB",
            "logoURI": "https://assets.coingecko.com/coins/images/825/small/binance-coin-logo.png?1547034615",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xcc",
            "blockExplorerUrls": [
                "https://opbnb.bscscan.com/",
                "https://opbnbscan.com/"
            ],
            "chainName": "opBNB Mainnet",
            "nativeCurrency": {
                "name": "BNB",
                "symbol": "BNB",
                "decimals": 18
            },
            "rpcUrls": [
                "https://opbnb-mainnet-rpc.bnbchain.org",
                "https://1rpc.io/opbnb"
            ]
        }
    },
    {
        "id": 21000000,
        "name": "Corn",
        "key": "crn",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/corn.svg",
        "nativeToken": {
            "symbol": "BTCN",
            "decimals": 18,
            "name": "Bitcorn",
            "logoURI": "https://static.debank.com/image/corn_token/logo_url/corn/fe230e468272b84aba78d08bb4140456.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x1406f40",
            "blockExplorerUrls": [
                "https://cornscan.io/"
            ],
            "chainName": "Corn",
            "nativeCurrency": {
                "name": "Bitcorn",
                "symbol": "BTCN",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.corn-rpc.com"
            ]
        }
    },
    {
        "id": 232,
        "name": "Lens",
        "key": "lns",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/lens.svg",
        "nativeToken": {
            "symbol": "GHO",
            "decimals": 18,
            "name": "GHO",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/23508.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xe8",
            "blockExplorerUrls": [
                "https://explorer.lens.xyz/"
            ],
            "chainName": "Lens",
            "nativeCurrency": {
                "name": "GHO",
                "symbol": "GHO",
                "decimals": 18
            },
            "rpcUrls": [
                "https://api.lens.matterhosted.dev"
            ]
        }
    },
    {
        "id": 25,
        "name": "Cronos",
        "key": "cro",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/cronos.svg",
        "nativeToken": {
            "symbol": "CRO",
            "decimals": 18,
            "name": "CRO",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x19",
            "blockExplorerUrls": [
                "https://explorer.cronos.org/",
                "https://cronoscan.com/"
            ],
            "chainName": "Cronos Mainnet",
            "nativeCurrency": {
                "name": "Cronos",
                "symbol": "CRO",
                "decimals": 18
            },
            "rpcUrls": [
                "https://evm.cronos.org",
                "https://cronos.drpc.org"
            ]
        }
    },
    {
        "id": 252,
        "name": "Fraxtal",
        "key": "fra",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/fraxtal.svg",
        "nativeToken": {
            "symbol": "FRAX",
            "decimals": 18,
            "name": "FRAX",
            "logoURI": "https://static.debank.com/image/movr_token/logo_url/0x965f84d915a9efa2dd81b653e3ae736555d945f4/1f2c42cba1add081f314ee899ab67816.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xfc",
            "blockExplorerUrls": [
                "https://fraxscan.com/"
            ],
            "chainName": "Fraxtal",
            "nativeCurrency": {
                "name": "FRAX",
                "symbol": "FRAX",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.frax.com",
                "https://fraxtal.gateway.tenderly.co"
            ]
        }
    },
    {
        "id": 2741,
        "name": "Abstract",
        "key": "abs",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/abstract.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xab5",
            "blockExplorerUrls": [
                "https://abscan.org/"
            ],
            "chainName": "Abstract",
            "nativeCurrency": {
                "name": "Ethereum",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://api.mainnet.abs.xyz"
            ]
        }
    },
    {
        "id": 288,
        "name": "Boba",
        "key": "bob",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/boba.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x120",
            "blockExplorerUrls": [
                "https://bobascan.com/"
            ],
            "chainName": "Boba Network",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.boba.network",
                "https://replica.boba.network"
            ]
        }
    },
    {
        "id": 30,
        "name": "Rootstock",
        "key": "rsk",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/rootstock.svg",
        "nativeToken": {
            "symbol": "RBTC",
            "decimals": 18,
            "name": "Rootstock Smart Bitcoin",
            "logoURI": "https://static.debank.com/image/rsk_token/logo_url/0x542fda317318ebf1d3deaf76e0b632741a7e677d/4785a26ef5bb5df987e67ad49fc62137.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x1e",
            "blockExplorerUrls": [
                "https://explorer.rootstock.io/"
            ],
            "chainName": "Rootstock Mainnet",
            "nativeCurrency": {
                "name": "Rootstock Smart Bitcoin",
                "symbol": "RBTC",
                "decimals": 18
            },
            "rpcUrls": [
                "https://public-node.rsk.co",
                "https://mycrypto.rsk.co"
            ]
        }
    },
    {
        "id": 324,
        "name": "zkSync",
        "key": "era",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/zksync.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x144",
            "blockExplorerUrls": [
                "https://explorer.zksync.io/"
            ],
            "chainName": "zkSync Mainnet",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.era.zksync.io"
            ]
        }
    },
    {
        "id": 33139,
        "name": "Apechain",
        "key": "ape",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/apechain.svg",
        "nativeToken": {
            "symbol": "APE",
            "decimals": 18,
            "name": "APE",
            "logoURI": "https://static.debank.com/image/ape_token/logo_url/ape/2357165eac1453c46f526704b51a801b.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x8173",
            "blockExplorerUrls": [
                "https://apescan.io/"
            ],
            "chainName": "ApeChain",
            "nativeCurrency": {
                "name": "ApeCoin",
                "symbol": "APE",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.apechain.com"
            ]
        }
    },
    {
        "id": 34443,
        "name": "Mode",
        "key": "mod",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/mode.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x868b",
            "blockExplorerUrls": [
                "https://explorer.mode.network/",
                "https://modescan.io/"
            ],
            "chainName": "Mode",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.mode.network",
                "https://mode.drpc.org"
            ]
        }
    },
    {
        "id": 42220,
        "name": "Celo",
        "key": "cel",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/celo.svg",
        "nativeToken": {
            "symbol": "CELO",
            "decimals": 18,
            "name": "Celo native asset",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/5567.png",
            "address": "0x471EcE3750Da237f93B8E339c536989b8978a438"
        },
        "metamask": {
            "chainId": "0xa4ec",
            "blockExplorerUrls": [
                "https://celoscan.io/"
            ],
            "chainName": "Celo Mainnet",
            "nativeCurrency": {
                "name": "CELO",
                "symbol": "CELO",
                "decimals": 18
            },
            "rpcUrls": [
                "https://forno.celo.org",
                "https://celo.drpc.org"
            ]
        }
    },
    {
        "id": 42793,
        "name": "Etherlink",
        "key": "etl",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/etherlink.svg",
        "nativeToken": {
            "symbol": "XTZ",
            "decimals": 18,
            "name": "Tezos",
            "logoURI": "https://assets.coingecko.com/coins/images/976/standard/Tezos-logo.png?1696502091",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xa729",
            "blockExplorerUrls": [
                "https://explorer.etherlink.com/"
            ],
            "chainName": "Etherlink",
            "nativeCurrency": {
                "name": "Tezos",
                "symbol": "XTZ",
                "decimals": 18
            },
            "rpcUrls": [
                "https://node.mainnet.etherlink.com"
            ]
        }
    },
    {
        "id": 43111,
        "name": "Hemi",
        "key": "hmi",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/hemi.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xa867",
            "blockExplorerUrls": [
                "https://explorer.hemi.xyz/"
            ],
            "chainName": "Hemi",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.hemi.network/rpc"
            ]
        }
    },
    {
        "id": 480,
        "name": "World Chain",
        "key": "wcc",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/world.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x1e0",
            "blockExplorerUrls": [
                "https://worldscan.org/"
            ],
            "chainName": "Worldchain Mainnet",
            "nativeCurrency": {
                "name": "Ethereum",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://worldchain-mainnet.g.alchemy.com/public",
                "https://worldchain-mainnet.gateway.tenderly.co"
            ]
        }
    },
    {
        "id": 50,
        "name": "XDC",
        "key": "xdc",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/xdc.svg",
        "nativeToken": {
            "symbol": "XDC",
            "decimals": 18,
            "name": "XDC",
            "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/xdc.svg",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x32",
            "blockExplorerUrls": [
                "https://xdcscan.com/"
            ],
            "chainName": "XDC",
            "nativeCurrency": {
                "name": "XDC",
                "symbol": "XDC",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.xdcrpc.com"
            ]
        }
    },
    {
        "id": 5000,
        "name": "Mantle",
        "key": "mnt",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/mantle.svg",
        "nativeToken": {
            "symbol": "MNT",
            "decimals": 18,
            "name": "MNT",
            "logoURI": "https://static.debank.com/image/mnt_token/logo_url/0x78c1b0c915c4faa5fffa6cabf0219da63d7f4cb8/a443c78c33704d48f06e5686bb87f85e.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x1388",
            "blockExplorerUrls": [
                "https://explorer.mantle.xyz/",
                "https://mantlescan.xyz/"
            ],
            "chainName": "Mantle",
            "nativeCurrency": {
                "name": "Mantle",
                "symbol": "MNT",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.mantle.xyz",
                "https://mantle-rpc.publicnode.com",
                "https://mantle.drpc.org",
                "https://mantle.public-rpc.com"
            ]
        }
    },
    {
        "id": 50104,
        "name": "Sophon",
        "key": "sop",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/sophon.svg",
        "nativeToken": {
            "symbol": "SOPH",
            "decimals": 18,
            "name": "Sophon",
            "logoURI": "https://static.debank.com/image/sophon_token/logo_url/sophon/b81ad042ee3060050e01af4ce4ff9217.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xc3b8",
            "blockExplorerUrls": [
                "https://sophscan.xyz/"
            ],
            "chainName": "Sophon",
            "nativeCurrency": {
                "name": "SOPH",
                "symbol": "SOPH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.sophon.xyz"
            ]
        }
    },
    {
        "id": 534352,
        "name": "Scroll",
        "key": "scl",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/scroll.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x82750",
            "blockExplorerUrls": [
                "https://scrollscan.com/"
            ],
            "chainName": "Scroll",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.scroll.io",
                "https://scroll.drpc.org",
                "https://scroll-mainnet.public.blastapi.io",
                "https://1rpc.io/scroll"
            ]
        }
    },
    {
        "id": 55244,
        "name": "Superposition",
        "key": "sup",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/superposition.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xd7cc",
            "blockExplorerUrls": [
                "https://explorer.superposition.so/"
            ],
            "chainName": "Superposition",
            "nativeCurrency": {
                "name": "Ether",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.superposition.so"
            ]
        }
    },
    {
        "id": 57073,
        "name": "Ink",
        "key": "ink",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/ink.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xdef1",
            "blockExplorerUrls": [
                "https://explorer.inkonchain.com/"
            ],
            "chainName": "Ink",
            "nativeCurrency": {
                "name": "Ether",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc-gel.inkonchain.com"
            ]
        }
    },
    {
        "id": 59144,
        "name": "Linea",
        "key": "lna",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/linea.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xe708",
            "blockExplorerUrls": [
                "https://lineascan.build/"
            ],
            "chainName": "Linea",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.linea.build"
            ]
        }
    },
    {
        "id": 60808,
        "name": "BOB",
        "key": "boc",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bob.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xed88",
            "blockExplorerUrls": [
                "https://explorer.gobob.xyz/"
            ],
            "chainName": "BOB",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.gobob.xyz"
            ]
        }
    },
    {
        "id": 747,
        "name": "Flow",
        "key": "flw",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/flow.svg",
        "nativeToken": {
            "symbol": "FLOW",
            "decimals": 18,
            "name": "Flow",
            "logoURI": "https://raw.githubusercontent.com/onflow/assets/main/tokens/registry/0xd3bF53DAC106A0290B0483EcBC89d40FcC961f3e/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x2eb",
            "blockExplorerUrls": [
                "https://evm.flowscan.io/"
            ],
            "chainName": "Flow EVM Mainnet",
            "nativeCurrency": {
                "name": "FLOW",
                "symbol": "FLOW",
                "decimals": 18
            },
            "rpcUrls": [
                "https://mainnet.evm.nodes.onflow.org"
            ]
        }
    },
    {
        "id": 747474,
        "name": "Katana",
        "key": "kat",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/katana.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0xb67d2",
            "blockExplorerUrls": [
                "https://katanascan.com/"
            ],
            "chainName": "Katana",
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.katana.network"
            ]
        }
    },
    {
        "id": 80094,
        "name": "Berachain",
        "key": "ber",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/bera.svg",
        "nativeToken": {
            "symbol": "BERA",
            "decimals": 18,
            "name": "BERA",
            "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/tokens/bera.svg",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x138de",
            "blockExplorerUrls": [
                "https://berascan.com/",
                "https://beratrail.io/"
            ],
            "chainName": "Berachain",
            "nativeCurrency": {
                "name": "Bera",
                "symbol": "BERA",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.berachain.com"
            ]
        }
    },
    {
        "id": 81457,
        "name": "Blast",
        "key": "bls",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/blast.svg",
        "nativeToken": {
            "symbol": "ETH",
            "decimals": 18,
            "name": "ETH",
            "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x13e31",
            "blockExplorerUrls": [
                "https://blastscan.io/",
                "https://blastexplorer.io/"
            ],
            "chainName": "Blast",
            "nativeCurrency": {
                "name": "Ethereum",
                "symbol": "ETH",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.blast.io",
                "https://blast-rpc.publicnode.com",
                "https://blast.drpc.org"
            ]
        }
    },
    {
        "id": 8217,
        "name": "Kaia",
        "key": "kai",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/kaia.svg",
        "nativeToken": {
            "symbol": "KAIA",
            "decimals": 18,
            "name": "KAIA",
            "logoURI": "https://static.debank.com/image/chain/logo_url/klay/4182ee077031d843a57e42746c30c072.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x2019",
            "blockExplorerUrls": [
                "https://kaiascan.io/"
            ],
            "chainName": "Kaia Mainnet",
            "nativeCurrency": {
                "name": "KAIA",
                "symbol": "KAIA",
                "decimals": 18
            },
            "rpcUrls": [
                "https://public-en.node.kaia.io",
                "https://klaytn.drpc.org"
            ]
        }
    },
    {
        "id": 88,
        "name": "Viction",
        "key": "vic",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/viction.svg",
        "nativeToken": {
            "symbol": "VIC",
            "decimals": 18,
            "name": "Viction",
            "logoURI": "https://assets.coingecko.com/coins/images/3416/standard/viction.jpeg?1698894318",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x58",
            "blockExplorerUrls": [
                "https://www.vicscan.xyz/"
            ],
            "chainName": "Viction",
            "nativeCurrency": {
                "name": "Viction",
                "symbol": "VIC",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.viction.xyz"
            ]
        }
    },
    {
        "id": 9745,
        "name": "Plasma",
        "key": "pla",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/plasma.svg",
        "nativeToken": {
            "symbol": "XPL",
            "decimals": 18,
            "name": "Plasma",
            "logoURI": "https://s2.coinmarketcap.com/static/img/coins/64x64/36645.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x2611",
            "blockExplorerUrls": [
                "https://plasmascan.to/"
            ],
            "chainName": "Plasma",
            "nativeCurrency": {
                "name": "XPL",
                "symbol": "XPL",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.plasma.to"
            ]
        }
    },
    {
        "id": 98866,
        "name": "Plume",
        "key": "plu",
        "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/chains/plume.svg",
        "nativeToken": {
            "symbol": "PLUME",
            "decimals": 18,
            "name": "Plume",
            "logoURI": "https://static.debank.com/image/plume_token/logo_url/plume/20ecb01558edaac59ad4cd20b9ccc51d.png",
            "address": "0x0000000000000000000000000000000000000000"
        },
        "metamask": {
            "chainId": "0x18232",
            "blockExplorerUrls": [
                "https://explorer.plume.org/"
            ],
            "chainName": "Plume",
            "nativeCurrency": {
                "name": "PLUME",
                "symbol": "PLUME",
                "decimals": 18
            },
            "rpcUrls": [
                "https://rpc.plume.org"
            ]
        }
    }
];
